### ISSUE TITLE
Probably shouldn't shadow `process`

### ISSUE THREAD

**Issue by jskrzypek** [davidnussio/vscode-jq-playground#1]
In [`jqCommand()`](https://github.com/davidnussio/vscode-jq-playground/blob/master/src/extension.ts#L195-L207) you declare a block-scoped `process` const var. YMMV, but this seems like a potentially dangerous practice as it shadows the node global `process`. I think a better practice would be to pick a different variable name like `childProcess` or `jqProcess`.

**Comment by davidnussio** [comment]
You're absolutely right, I will fix it. Thanks!
