### ISSUE TITLE
Request: Support getting filter from an unsaved temporary file

### ISSUE THREAD

**Issue by Phrohdoh** [davidnussio/vscode-jq-playground#21]
It would be useful to support the following:

```
jq Untitled-2
Untitled-1
```

Where the filter `Untitled-2` is checked against open buffer names and if one is found use the contents of the found buffer as the filter, if not use `Untitled-2` literally.

**Comment by davidnussio** [comment]
Do you want use a jq query from unsaved file to support multiline query?

**Comment by Phrohdoh** [comment]
Supporting multi-line queries would be nice regardless of where they originate but that wasn't specifically the purpose of this request.

**Comment by davidnussio** [comment]
![2020-04-26_21-08](https://user-images.githubusercontent.com/324371/80317126-317fe980-8802-11ea-90c1-ad97bad153d3.png)

It is going to be released with the next update
