### ISSUE TITLE
Arguments inline option not working

### ISSUE THREAD

**Issue by moinessim** [davidnussio/vscode-jq-playground#26]
##### Command line: 
```jq
echo '{}' | jq --arg var val '.value = $var'
```
>  { "value": "val"}

##### Playground:
```jq
jq --arg var val '.value = $var'
{}
```
>  [ERROR] - /.../.vscode/extensions/davidnussio.vscode-jq-playground-2.1.1/bin/jq: --arg takes two parameters (e.g. --arg varname value)
Use /.../.vscode/extensions/davidnussio.vscode-jq-playground-2.1.1/bin/jq --help for help with command-line options,
[ERROR] - or see the jq manpage, or online docs  at https://stedolan.github.io/jq

**Comment by davidnussio** [comment]
![2020-04-26_21-22](https://user-images.githubusercontent.com/324371/80317445-144c1a80-8804-11ea-9d9d-3f2a2e63310c.png)

It is going to be released with the next update
