### ISSUE TITLE
Multiline jq query

### ISSUE THREAD

**Issue by bendem** [davidnussio/vscode-jq-playground#27]
jq queries tend to get lengthy and unreadable on a single line. Is there a way to allow multi-line queries (maybe based on indentation, or using a `\` at the end of the line) ?

Something like this maybe?
```bash
jq .[] | select(.prerelease == false) | {
        windows: (select(.tag_name | startswith("window")) | .assets[].browser_download_url),
        linux: (select(.tag_name | startswith("linux")) | .assets[].browser_download_url),
        mac: (select(.tag_name | startswith("mac")) | .assets[].browser_download_url)
    }
[
  {
...
  }
]
```

**Comment by davidnussio** [comment]
Yes, It make sense. I like the idea of \ at the end of the line and 
both for simplicity and for compatibility with the command line.

**Comment by davidnussio** [comment]
![2020-04-26_21-26](https://user-images.githubusercontent.com/324371/80317530-abb16d80-8804-11ea-99f7-11d7990732d1.png)

It is going to be released with the next update

**Comment by jiucenglou** [comment]
> Yes, It make sense. I like the idea of \ at the end of the line and
> both for simplicity and for compatibility with the command line.

Could the usage be more compatible with jq on the command line and https://jqplay.org/, i.e., eliminating backslash ?

The reason is that on the command line (e.g., bash), jq query is generally contained within single quotes, and therefore actually does not need backslash to continue. Furthermore, the backslash makes it rather difficult to try the same query in https://jqplay.org/.

**Comment by davidnussio** [comment]
Uhm, I understand...

**Comment by davidnussio** [comment]
Uhm, I understand...
Initially I didn't inserted jq filter into single quote string, in this way for the user the experience was like to written in a script file.
I tried to not add special token to separate jq filter from data but now maybe this idea is better than the backslash.

```
jq filter
---
{
 ...
}
```

_My idea:_

Adding separation token into jq playground token. Default empty and support \ (backward compatibility)
Let user configure token to separate jq filter from data (as above three hyphens ---)

Any ideas?

**Comment by jiucenglou** [comment]
```
EMPTY LINE
CMD PARAMETERS (--slurp etc), multi-line, till jq
jq 
JQ FILTER, multi-line, till next EMPTY LINE
```
Would this be plausible ?

**Comment by bendem** [comment]
or mimick the terminal and allow quotes to make the jq expression multiline, that way you can copy paste directly from the file to the console

**Comment by jiucenglou** [comment]
It looks that jqplay updates the command line when ever the filter is updated. Maybe this could be done to be compatible also with command line?

**Comment by davidnussio** [comment]
**Case 1)** mimic terminal (I think this is better than backslash on every line)
```
⚡ ➜ console | ⚡ ➜ editor
jq '
[
    foreach .[] as $item (
        [[],[]]; 
        if $item == null then [[],.[0]] else [(.[0] + [$item]),[]] end; 
        if $item == null then .[1] else empty end
    )
]
'
[1,2,3,4,null,"a","b",null]

⚡ ➜ console | ⚡ ➜ editor
jq [.[] | . + 1]
[1,3,5,7]
```

**Case 2)** Separator (maybe could add copy to clipboard action)  
```
⚡ ➜ console | ⚡ ➜ editor | ⎘ command line
jq [
    foreach .[] as $item (
        [[],[]]; 
        if $item == null then [[],.[0]] else [(.[0] + [$item]),[]] end; 
        if $item == null then .[1] else empty end
    )
]
----
[1,2,3,4,null,"a","b",null]

⚡ ➜ console | ⚡ ➜ editor | ⎘ command line
jq '[
    foreach .[] as $item (
        [[],[]]; 
        if $item == null then [[],.[0]] else [(.[0] + [$item]),[]] end; 
        if $item == null then .[1] else empty end
    )
]'
----
[1,2,3,4,null,"a","b",null]
```

Maybe the best would be to support both.
The idea is to add ---- filter/input separator into vscode configuration and control between Case 1 and Case 2.

Case 1 work without quotes for one line filter or with quotes and let user to write multiline filter like into the terminal
Case 2 with filter/input separator support both filter with or without quotes.

In the next release case 2 will be disable by default to keep backward compatibility.

After that I will have to fight with the highlight code rules 😬
