### ISSUE TITLE
Hotkey to execute query in the current line

### ISSUE THREAD

**Issue by xak2000** [davidnussio/vscode-jq-playground#3]
Hi, thanks for the extension!

It would be very convinient to allow to execute the current query by pressing some hotkey instead of each time mouseovering on `jq -> to output` or `jq -> to editor`.

For example:

<kbd>CTRL-ENTER</kbd> jq -> to output
<kbd>SHIFT-ENTER</kbd> jq -> to editor

**Comment by davidnussio** [comment]
Today I published this enhancement.
