### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by rsilvestre** [davidnussio/vscode-jq-playground#31]
Hi,

I'm using 
VSCode - Insiders
Version: 1.46.0-insider
Commit: e1d8f5155c0db5ffdc130c9aa0f14efac02dfdfb
Date: 2020-05-13T20:32:52.338Z (1 day ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

I'm facing an issue with this tool.

I've got an error message in the jq output telling 
`Error: write EPIPE`

I was just trying to execute the examples coming from the extension.

[EDIT]
To complete:
I've got this error when I launch VSCode
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

```
Download jq binary for platform (darwin)
  - form url https://github.com/stedolan/jq/releases/download/jq-1.6/jq-osx-amd64
  - to dir /Users/me/Library/Application Support/Code/User/globalStorage/davidnussio.vscode-jq-playground
  - start downloading...

  - [ ERROR ]
  - Error: ENOENT: no such file or directory, open '/Users/me/Library/Application Support/Code/User/globalStorage/davidnussio.vscode-jq-playground/jq'

🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥
  Extension activation error!
 *** An error occurred during activation.
 *** Try again or download jq binary manually.
 *** Check vscode configuration → Jq Playground: Binary Pat
```

by the way, il have jq installed on my computer
and it looks that `/Users/me/Library/Application Support/Code/User/globalStorage/davidnussio.vscode-jq-playground/`really don't exist

So i created the folder and i've got an other error about checksum issue:
```
Download jq binary for platform (darwin)
  - form url https://github.com/stedolan/jq/releases/download/jq-1.6/jq-osx-amd64
  - to dir /Users/michaelsilvestre/Library/Application Support/Code/User/globalStorage/davidnussio.vscode-jq-playground
  - start downloading...


  - [ ERROR ]
  - Error: Download file checksum error

🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥
  Extension activation error!
 *** An error occurred during activation.
 *** Try again or download jq binary manually.
 *** Check vscode configuration → Jq Playground: Binary Pat
```

After investigation, I observe that you my checksum is : c15f86ad9298ee71cf7d96a29f86e88a and your is f2c7caa006dd3dff54f5c8adad3445ab

I also observe that you change the checksum 12 days ago in this commit : d60de755a91b5fa4366babfc959f81288317dccd

Any way I don't have time any more....

Regards,

**Comment by davidnussio** [comment]
Thank you, I fixed checksum hex codes for OSX and Windows platforms and released the fix.

**Comment by davidnussio** [comment]
Tested on OSX and Windows too.

**Comment by rsilvestre** [comment]
Great Job and Reactivity 🔥
