### ISSUE TITLE
Multiple file input

### ISSUE THREAD

**Issue by jordao76** [davidnussio/vscode-jq-playground#49]
It would be good to support multiple files as input.

**Comment by davidnussio** [comment]
I never used multiple files as input but it seem interesting feature.
Could you give me some command line examples?

Thanks

**Comment by jordao76** [comment]
Sure,

I need to concatenate certain JSON files into a single file, and make a JSON object where each key is the original file name and the value is the original file JSON.

I can do this for e.g. two files like this:

```bash
jq '{ (input_filename|rtrimstr(\".json\")) : . }' file1.json file2.json | jq -s add
```

I'm sure there's a way to do it in one `jq` command, but you get the idea.

What I actually do is read all files in a folder and do that:

```bash
ls -I data.json | xargs jq '{ (input_filename|rtrimstr(\".json\")) : . }' | jq -s add > data.json
```
