### ISSUE TITLE
on Windows 10 jqpg file cannot process local file.

### ISSUE THREAD

**Issue by alex-y-kozlov** [davidnussio/vscode-jq-playground#50]
Steps:

1) create a file c:\program\test.json
2) file contents ' {"foo": 42, "bar": "less interesting data"} '
3) open jq file in VSCode and type:
```
jq .foo
C:\program\test.json
```
4) click editor or console. get an error ` parse error: Invalid numeric literal at line 1, column `

**The same thing on the mac works fine. json file path is different: /Users/<username>/program/test.json**

**Comment by davidnussio** [comment]
Thank you for reporting the issue.
I just released a update patch that fix this issue.

I tested with absolute path and relative to the current working dir.

![2020-06-28_22-32](https://user-images.githubusercontent.com/324371/85958110-304e7280-b993-11ea-94a8-926b29adf2dc.png)

**Comment by alex-y-kozlov** [comment]
Just tried it. Confirmed, - works!
Wow! Your extension is GREAT~ but your turn around time is simply OUT OF THIS WORLD!
Amazing!
Thank you, David!
