### ISSUE TITLE
Editor output association is not JSON

### ISSUE THREAD

**Issue by phrozen** [davidnussio/vscode-jq-playground#53]
If I have a `.jq` or `.jqpg` file with the file association either with `jq` or `jqpg`, when using editor output, the new `Untitled` document has a default `jq` association which should be `JSON`. Is there a way to change this behavior so that syntax highlighting and beautify/prettier extensions work on output from the start? Also when trying to save the file, it will use a `.jq` extension automatically.

**Comment by davidnussio** [comment]
Make sense, thank you. I already released this change.

**Comment by phrozen** [comment]
Thank you! This change makes it an absolute pleasure to use the extension!
