### ISSUE TITLE
Add input variable support?

### ISSUE THREAD

**Issue by JeffreyMercado** [davidnussio/vscode-jq-playground#64]
Not sure if this is within the scope of this extension, but it would be nice if the extension had [input variable](https://code.visualstudio.com/docs/editor/variables-reference#_input-variables) support. Might be worth looking into, it would allow users to extract values from json files to insert into task or launch configurations.

**Comment by davidnussio** [comment]
At first I thought it was out of context of this extension but I use this extension every day in developing tasks and it could be useful in some cases. I will take a look.

**Comment by JeffreyMercado** [comment]
I'm working on getting a PR right now. In my tests it has been working but I'm trying to clean up and trying to appease the compiler can be tough some times. :)

https://github.com/JeffreyMercado/vscode-jq-playground/commits/feature/input-variable

Side question, how do you go about running the unit tests? I started creating some tests but couldn't figure out how to get it running.
