### ISSUE TITLE
Minor: mistargeted link on VSCode Marketplace

### ISSUE THREAD

**Issue by kkm000** [davidnussio/vscode-jq-playground#77]
https://marketplace.visualstudio.com/items?itemName=davidnussio.vscode-jq-playground
Overview, second paragraph from top

> Check jq tutorial or manual

Both "tutorial" and "manual" are links pointing to the same Jq tutorial page.

```html
<p>
Check jq <a href="https://stedolan.github.io/jq/tutorial/" target="_blank" rel="noreferrer noopener nofollow">tutorial</a>
      or <a href="https://stedolan.github.io/jq/tutorial/" target="_blank" rel="noreferrer noopener nofollow">manual</a>
</p>
```

**Note:** The Jq manuals, unlike the tutorial, are versioned. The link https://stedolan.github.io/jq/manual/v1.6/ is currently the best target for the Jq version 1.6, downloaded by the extension. https://stedolan.github.io/jq/manual/ without the version points to the dev version, with some documented features not yet even implemented.

**Comment by davidnussio** [comment]
Oh, thank you. Nice catch!
