### ISSUE TITLE
"Redirect output's filter" always append the data to the file

### ISSUE THREAD

**Issue by hgerii** [davidnussio/vscode-jq-playground#87]
The following command with `>` append the result to the file instead of overriding its content. That does the same as the `>>`.

`
jq '[.[].url]' > tmp.json
$ curl 'https://api.github.com/repos/stedolan/jq/commits?per_page=5'
`

That seems to be caused by the default value which is set to `true` at this line:

https://github.com/davidnussio/vscode-jq-playground/blob/07d08d33c83920f0b79849c7e59b845d20e13bd0/src/extension.ts#L363-L369

and see how that is used here:

https://github.com/davidnussio/vscode-jq-playground/blob/07d08d33c83920f0b79849c7e59b845d20e13bd0/src/extension.ts#L384-L388

**Comment by davidnussio** [comment]
Nice catch. Thank you!
