### ISSUE TITLE
[REQUEST] Use new API for OutputChannel

### ISSUE THREAD

**Issue by mxcoder** [davidnussio/vscode-jq-playground#88]
Thanks for your work on this extension, it has been very useful :)

Using [this feature](https://github.com/microsoft/vscode/issues/19561#issuecomment-1032641929) in this part of [the code](https://github.com/davidnussio/vscode-jq-playground/blob/8dec52c4fe6c1345731c2fa7c04a4fabea428560/src/logger.ts#L3) we can easily improve the result view.

I'd recommend setting either `json` or maybe `shell` to let `jq -C` do the coloring part.

**Comment by davidnussio** [comment]
Thank you!
